### PR TITLE
Fixed header on HomePage

### PR DESCRIPTION
**Pull request by Marce1ina**
#### Story / Bug id:
#365

#### Description:
Added layout markups for vuetify to make the HomePage Header stick to the top of display while scrolling through the page.
Added scrollactive lib to handle changing nav tab to active when scrolling.

#### Migrations:
N/A

#### New imports / dependencies:
https://www.npmjs.com/package/vue-scrollactive

#### What tests do I need to run to validate this change:
Manual - accordingly to description.

### CODE REVIEW

**Review by KSodowska — APPROVED** [review]
Hi, it runs smoothly :)

**Comment by KSodowska** [comment]
@OtisRed one thing considering header topic: right now on our main page, it highlights your position while scrolling, on localhost - it stays on 'O nas'.

header_main


obraz

**Comment by Marce1ina** [comment]
@KSodowska @OtisRed Scrolling issue should be fixed now, please check again.

**Review by KSodowska — APPROVED** [review]
Hi @Marce1ina, navigation tab works :)

**Comment by KSodowska** [comment]
@Marce1ina But at the same time, something minor came up, 'Strona społeczności' title doesn't adjust in a certain conditions (in the master it works fine). Pls check if you have the same 'problem'.

Both are in the same conditions: 
Webrowser: Firefox 88.0, Chrome 90.0 (Ubuntu)
Screen: 1366x768, 1360x768
Zoom: 100% (works fine when it's 90% and less,110% or more)

Master:
Strona społ master

Branch #376
Strona społ branch test_376

**Comment by Marce1ina** [comment]
@KSodowska I'm not able to reproduce this issue on MacOS (tried both Chrome and Firefox in same versions). Does it stay like this after page refresh for you? Think we would need another Ubuntu user to verify this.

**Comment by OtisRed** [comment]
@KSodowska please create a new ticket for this problem as it's out of the scope of this PR, yet still it would be good to investigate.
@Marce1ina it's unblocked now - sorry for the mistake

**Comment by KSodowska** [comment]
@OtisRed hi, I'll do it tomorrow. I want to check it out on RWD simulator first.

**Review by stanislawK — APPROVED** [review]
It would be nice to have same behavior without  external package

**Comment by OtisRed** [comment]
@stanislawK thanks for CR! This was a work around because Vuetify couldn't cut it for some reason. Also I think we could use these scroll-events for other purposes. I will create ticket so we can talk about possiblities of solvng this differently but for now I will merge it as a working solution :) 

@Marce1ina you just need to resolve conflivts because they block merging :)

**Comment by Marce1ina** [comment]
@stanislawK I didn't find any build-in solution for this in Vuetify and native intersection-observer API wasn't willing to cooperate so I used the external library. I know it would be nice to not have it, but considering how much time I've already spent on trying to make it work otherwise, it's just not worth the effort.

@OtisRed I've resolved conflicts so if you're ok with that, let's merge this PR.

**Pull request merged**
