### PR TITLE
[107] constant width of components

### PR DESCRIPTION
**Pull request by Loczi94**
Vuetify classes were added to AboutUs component.
Global class container with max-width was created.

### CODE REVIEW

**Comment by OtisRed** [comment]
I've checked and for some reason deleting "fluid" attribute from v-container somehow doesn't box the blue background anymore. So it seems we should achieve the aim of this task by simply deleting "fulid" attribute from blue containers.

**Comment by OtisRed** [comment]
You've got conflicts here, plus please make sure you merged current master into PR :)

**Comment by Loczi94** [comment]
@OtisRed done :)

**Comment by OtisRed** [comment]
@Loczi94 Now I've noticed that you've left fluid attribute in About us component :P Sorry, I didn't catch that before. I can delete it from here if you don't wanna look at it anymore :D

**Comment by OtisRed** [comment]
As we upgraded vuetify it doesn't work anymore plus I have a strong feeling that it will be solved along all the scss mess :D

**Pull request closed without merging**
