### PR TITLE
CC0 license image of magnifier glass

### PR DESCRIPTION
**Pull request by Tomasz1234**
Added a magnifying glass image with CC0 license.
Deleted old magnifying glass image.

### CODE REVIEW

**Comment by OtisRed** [comment]
Please describe shortly how would you test it. I know it seems unnecessary with regard to this change, but we try to provide such descriptions, that would allow sb without much prior knowledge to check whether it's right or wrong. Even visually, which is the case here. 

It's just a good habit, because as you see our biggest problem is to manage stock of pull requests, so we try to make testing them as easy as possible, so we could pull them more quickly.

**Comment by w1stler** [comment]
Source branch: master? ;-)

**Comment by w1stler** [comment]
`make rebuild` didn't work. 😢 

```cfp_v3_frontend |  ERROR  Failed to compile with 1 errors6:26:34 PM
cfp_v3_frontend |
cfp_v3_frontend | This dependency was not found:
cfp_v3_frontend |
cfp_v3_frontend | <s> [webpack.Progress] 100%
cfp_v3_frontend |
cfp_v3_frontend | * @/assets/images/Antu_dialog-icon-preview.svg in ./node_modules/vuetify-loader/lib/loader.js!./node_modules/@vue/cli-service/node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/components/OurProjects.vue?vue&type=script&lang=js&
cfp_v3_frontend |
cfp_v3_frontend | To install it, you can run: npm install --save @/assets/images/Antu_dialog-icon-preview.svg```

**Comment by magul** [comment]
This one `require` should point to new icon: https://github.com/CodeForPoznan/codeforpoznan.pl_v3/blob/874b57bb7bf80342ea2c04b689ddbf8dae02f6ae/frontend/src/components/OurProjects.vue#L34

**Comment by OtisRed** [comment]
Closed with consultation with the author - this will be PRed again.

**Pull request closed without merging**
