### PR TITLE
401: add google analytics

### PR DESCRIPTION
**Pull request by arturtamborski**
#### Story / Bug id:
#401 

#### Description:
Add google analytics

#### Migrations:
N/A

#### New imports / dependencies:
N/A

#### What tests do I need to run to validate this change:
after deployment to dev, this change should populate Google Analytics dashboard.

### CODE REVIEW

**Comment by arturtamborski** [comment]
ready for review, might be difficult to test though because we don't have access to the GA console (@magul can you add people there somehow?)

**Comment by OtisRed** [comment]
@magul are you able to check this solution and/or preferably admit access for someone to GA console? :D

**Review by w1stler — APPROVED** [review]

**Review by magul — APPROVED** [review]

**Comment by OtisRed** [comment]
@arturtamborski please merge if you feel like it's ready (you've got personal access to check GA as well)

**Comment by arturtamborski** [comment]
thanks for the approval and access to google analytics console :)

This PR will need to wait though, because there's a bug in my code. I discovered it recently by testing this code on a temporary setup i made in the meantime.

basically GA will always stay disabled, because the CI system (yarn) does not build the app in production mode when it goes to prod.

**Comment by arturtamborski** [comment]
this is now unblocked thanks to v2 release of actions.

**Comment by arturtamborski** [comment]
This PR is now ready to test and merge. I need someone to check if the project (frontend) works correctly, since I'm regenerating the yarn.lock file.

Right after this one gets merged we will need to merge this: https://github.com/CodeForPoznan/codeforpoznan.pl_v3/pull/509

**Pull request merged**
