### PR TITLE
[201] Cleanup in login endpoint

### PR DESCRIPTION
**Pull request by moniabak**
Deleted 3 lines from auth.py file.

        if not (username and password):
            return {"msg": "Username and password required"},
            HTTPStatus.BAD_REQUEST

### CODE REVIEW

**Comment by moniabak** [comment]
Ok I will remember that. I didn't and don't know the pattern for naming branches. Do you have any ? number_case or else? I forgot to ask

**Comment by w1stler** [comment]
We loosely adapt these rules: https://github.com/CodeForPoznan/Community/blob/master/technical_onboarding/working_agreement.md

**Comment by moniabak** [comment]
Ok thank you

**Comment by w1stler** [comment]
Please resolve conflicts.

**Comment by moniabak** [comment]
done !

**Comment by stanislawK** [comment]
@magul I belive those changes are valid - both username and password are required fields in marshmallow schema, and few lines above we validate it:
```
        try:
            result = schema.load(request.json)
        except ValidationError as error:
            return (
                {"msg": "Wrong input data", "errors": error.messages},
                HTTPStatus.BAD_REQUEST,
            )
```
so imo there is no reason to check it manually second time.

**Pull request merged**
